services:

  node-frontend:
    build:
      context: ./node-frontend

    container_name: node-frontend

    ports:
      - "3000:3000"

    depends_on:
      - otel-collector


  python-orders:
    build:
      context: ./python-orders

    container_name: python-orders

    ports:
      - "8000:8000"

    depends_on:
      - otel-collector


  go-inventory:
    build:
      context: ./go-inventory

    container_name: go-inventory

    ports:
      - "8080:8080"

    depends_on:
      - otel-collector

    environment:
      OTEL_SERVICE_NAME: go-inventory
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest

    container_name: otel-collector

    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ap1.datadoghq.com

    command:
      - "--config=/etc/otelcol-contrib/config.yaml"

    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml

    ports:
      - "4317:4317"
      - "4318:4318"