name: Build, Scan and Push Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.env.example'
      - 'LICENSE'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'images/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    env:
      GHCR_OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v7

      - name: Generate short SHA tag
        run: |
          echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build latest images
        env:
          IMAGE_TAG: latest
        run: docker compose build

      - name: Tag SHA images
        run: |
          docker tag ghcr.io/${GHCR_OWNER}/node-frontend:latest ghcr.io/${GHCR_OWNER}/node-frontend:${SHORT_SHA}
          docker tag ghcr.io/${GHCR_OWNER}/python-orders:latest ghcr.io/${GHCR_OWNER}/python-orders:${SHORT_SHA}
          docker tag ghcr.io/${GHCR_OWNER}/go-inventory:latest ghcr.io/${GHCR_OWNER}/go-inventory:${SHORT_SHA}

      # - name: Run Trivy Filesystem Scan
      #   uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      #   with:
      #     scan-type: fs
      #     scan-ref: .
      #     scanners: vuln,misconfig
      #     format: sarif
      #     severity: HIGH,CRITICAL
      #     output: trivy-fs.sarif
      #     exit-code: 0

      - name: Upload Filesystem SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      - name: Scan node-frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/node-frontend:latest
          format: sarif
          scanners: vuln,misconfig
          severity: HIGH,CRITICAL
          output: trivy-node-frontend.sarif
          ignore-unfixed: true
          exit-code: 0

      - name: Upload node-frontend SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-node-frontend.sarif
          category: node-frontend

      - name: Scan python-orders image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/python-orders:latest
          format: sarif
          scanners: vuln,misconfig
          severity: HIGH,CRITICAL
          output: trivy-python-orders.sarif
          ignore-unfixed: true
          exit-code: 0

      - name: Upload python-orders SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-python-orders.sarif
          category: python-orders

      - name: Scan go-inventory image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/go-inventory:latest
          format: sarif
          scanners: vuln,misconfig
          severity: HIGH,CRITICAL
          output: trivy-go-inventory.sarif
          ignore-unfixed: true
          exit-code: 0

      - name: Upload go-inventory SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-go-inventory.sarif
          category: go-inventory

      - name: Generate Node Frontend SBOM
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/node-frontend:latest
          format: cyclonedx
          output: node-frontend-sbom.json

      - name: Generate Python Orders SBOM
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/python-orders:latest
          format: cyclonedx
          output: python-orders-sbom.json

      - name: Generate Go Inventory SBOM
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/go-inventory:latest
          format: cyclonedx
          output: go-inventory-sbom.json

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            node-frontend-sbom.json
            python-orders-sbom.json
            go-inventory-sbom.json

      - name: Upload Node Frontend Image Results to DefectDojo
        if: always()
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=SARIF" \
            -F "file=@trivy-node-frontend.sarif" \
            -F "auto_create_context=true" \
            -F "product_type_name=SecOrg" \
            -F "product_name=TestAsset" \
            -F "engagement_name=TestEngagement" \
            -F "test_title=TrivyNodeFrontendImage" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=Lab" \
            -F "build_id=${{ github.run_number }}" \
            -F "branch_tag=${{ github.ref_name }}" \
            -F "commit_hash=${{ github.sha }}" \
            -F "tags=github-actions,trivy,image,node-frontend,${{ github.ref_name }}"

      - name: Upload Python Orders Image Results to DefectDojo
        if: always()
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=SARIF" \
            -F "file=@trivy-python-orders.sarif" \
            -F "auto_create_context=true" \
            -F "product_type_name=SecOrg" \
            -F "product_name=TestAsset" \
            -F "engagement_name=TestEngagement" \
            -F "test_title=TrivyPythonOrdersImage" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=Lab" \
            -F "build_id=${{ github.run_number }}" \
            -F "branch_tag=${{ github.ref_name }}" \
            -F "commit_hash=${{ github.sha }}" \
            -F "tags=github-actions,trivy,image,python-orders,${{ github.ref_name }}"

      - name: Upload Go Inventory Image Results to DefectDojo
        if: always()
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=SARIF" \
            -F "file=@trivy-go-inventory.sarif" \
            -F "auto_create_context=true" \
            -F "product_type_name=SecOrg" \
            -F "product_name=TestAsset" \
            -F "engagement_name=TestEngagement" \
            -F "test_title=TrivyGoInventoryImage" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=Lab" \
            -F "build_id=${{ github.run_number }}" \
            -F "branch_tag=${{ github.ref_name }}" \
            -F "commit_hash=${{ github.sha }}" \
            -F "tags=github-actions,trivy,image,go-inventory,${{ github.ref_name }}"

      - name: Push latest images
        env:
          IMAGE_TAG: latest
        run: docker compose push

      - name: Push SHA images
        run: |
          docker push ghcr.io/${GHCR_OWNER}/node-frontend:${SHORT_SHA}
          docker push ghcr.io/${GHCR_OWNER}/python-orders:${SHORT_SHA}
          docker push ghcr.io/${GHCR_OWNER}/go-inventory:${SHORT_SHA}

      - name: Checkout manifest repo
        uses: actions/checkout@v7
        with:
          repository: sagarkpanda/otel-labs-platform
          token: ${{ secrets.PLATFORM_REPO_TOKEN }}
          path: otel-labs-platform

      - name: Update image tags in manifest repo
        run: |
          cd otel-labs-platform

          sed -i "s/newTag:.*/newTag: \"${SHORT_SHA}\"/" \
            k8s/node-frontend/kustomization.yml

          sed -i "s/newTag:.*/newTag: \"${SHORT_SHA}\"/" \
            k8s/python-orders/kustomization.yml

          sed -i "s/newTag:.*/newTag: \"${SHORT_SHA}\"/" \
            k8s/go-inventory/kustomization.yml

      - name: Commit and push manifest changes
        run: |
          cd otel-labs-platform

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update image tags to ${SHORT_SHA}"

          git push
