name: Semgrep

on:
  push:
    branches: [main]
    paths:
      - 'node-frontend/**'
      - 'python-orders/**'
      - 'go-inventory/**'
      - 'otel-collector/**'
      - '.github/workflows/semgrep.yml'
      
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: SAST Scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Semgrep
        continue-on-error: true
        run: |
          semgrep scan --config auto --sarif --output semgrep.sarif .

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a
        with:
          sarif_file: semgrep.sarif

      - name: Upload SARIF Artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: semgrep-sarif
          path: semgrep.sarif

      - name: Upload to DefectDojo
        if: always()
        run: |
          RESPONSE=$(curl --fail --show-error --silent \
            -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=SARIF" \
            -F "file=@semgrep.sarif" \
            -F "auto_create_context=true" \
            -F "product_type_name=SP Org" \
            -F "product_name=Otel Labs" \
            -F "engagement_name=App Sec Engagement" \
            -F "test_title=Semgrep" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=Lab" \
            -F "build_id=${{ github.run_number }}" \
            -F "branch_tag=${{ github.ref_name }}" \
            -F "commit_hash=${{ github.sha }}" \
            -F "tags=github-actions,semgrep,${{ github.ref_name }}")
          echo "$RESPONSE"